version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_financier
    restart: unless-stopped
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=financier
      - POSTGRES_USER=${POSTGRES_FINANCIER_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_FINANCIER_PASSWORD}
