name: pipeline
on: [ push ]
jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for back
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: 19
          distribution: adopt
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew test :financier-app:build --stacktrace
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
#      - run: cd front/
      - run: npm i
        with:
          paths: front
      - run: npm run build
        with:
          paths: front
