name: pipeline
on: [ push ]
jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for back
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: 19
          distribution: adopt
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew test :financier-app:build --stacktrace
