name: pipeline
on: [ push ]
jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for back
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: temurin
          cache: gradle
      - name: Build back
        run: ./gradlew test :financier-app:build --stacktrace

  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout for front
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: front/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Build front
        run: npm run build
