name: pipeline
on: [ push ]
jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for back
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew test :financier-app:build --stacktrace
  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
          cache-dependency-path: front/package-lock.json
      - run: npm -v
      - run: node -v
      - run: pwd
